#include <common.h>
#include <string.h>

#ifdef printf
#undef printf
#endif
#include <stdio.h>

static unsigned short quot1[3] = {0}; /* quot[0]:baud_div, quot[1]:umr, quot[2]:uacr */

static struct baudtoregs_t
{
    unsigned int baud;
    unsigned short div;
    unsigned int umr:5;
    unsigned int uacr:12;
} baudtoregs[] = {
    /*
      The data is generated by a python,
      the script is tools/tty/get_divisor.py
     */
 #if (CONFIG_EXTAL_FREQ == 24)
    {50,0x7530,0x10,0x0},
    {75,0x4e20,0x10,0x0},
    {110,0x3521,0x10,0x0},
    {134,0x2b9d,0x10,0x0},
    {150,0x2710,0x10,0x0},
    {200,0x1d4c,0x10,0x0},
    {300,0x1388,0x10,0x0},
    {600,0x9c4,0x10,0x0},
    {1200,0x4e2,0x10,0x0},
    {1800,0x340,0x10,0x0},
    {2400,0x271,0x10,0x0},
    {4800,0x138,0x10,0x0},
    {9600,0x9c,0x10,0x0},
    {19200,0x4e,0x10,0x0},
    {38400,0x27,0x10,0x0},
    {57600,0x1a,0x10,0x0},
    {115200,0xd,0x10,0x0},
    {230400,0x6,0x11,0x550},
    {460800,0x3,0x11,0x550},
    {500000,0x3,0x10,0x0},
    {576000,0x3,0xd,0x0},
    {921600,0x2,0xd,0x0},
    {1000000,0x2,0xc,0x0},
    {1152000,0x1,0x14,0x400},
    {1500000,0x1,0x10,0x0},
    {2000000,0x1,0xc,0x0},
    {2500000,0x1,0x9,0x780},
    {3000000,0x1,0x8,0x0},
    {3500000,0x1,0x6,0x400},
    {4000000,0x1,0x6,0x0},
#elif (CONFIG_EXTAL_FREQ == 26)
    {50,0x7ef4,0x10,0x0},
    {75,0x546b,0x10,0x0},
    {110,0x398f,0x10,0x0},
    {134,0x2f40,0x10,0x0},
    {150,0x2a36,0x10,0x0},
    {200,0x1fbd,0x10,0x0},
    {300,0x151b,0x10,0x0},
    {600,0xa8e,0x10,0x0},
    {1200,0x547,0x10,0x0},
    {1800,0x385,0x10,0x0},
    {2400,0x2a4,0x10,0x0},
    {4800,0x152,0x10,0x0},
    {9600,0xa9,0x10,0x0},
    {19200,0x54,0x10,0x2},
    {38400,0x2a,0x10,0x2},
    {57600,0x1c,0x10,0x2},
    {115200,0xe,0x10,0x2},
    {230400,0x7,0x10,0x2},
    {460800,0x4,0xe,0x2},
    {500000,0x3,0x11,0x550},
    {576000,0x3,0xf,0x2},
    {921600,0x2,0xe,0x2},
    {1000000,0x2,0xd,0x0},
    {1152000,0x2,0xb,0x248},
    {1500000,0x1,0x11,0x550},
    {2000000,0x1,0xd,0x0},
    {2500000,0x1,0xa,0x2a0},
    {3000000,0x1,0x8,0x700},
    {3500000,0x1,0x7,0x2a0},
    {4000000,0x1,0x6,0x7c0},
#endif
};

void *bsearch(const void *key, const void *base, size_t num, size_t size,
          int (*cmp)(const void *key, const void *elt))
{
    size_t start = 0, end = num;
    int result;

    while (start < end) {
        size_t mid = start + (end - start) / 2;

        result = cmp(key, base + mid * size);
        if (result < 0)
            end = mid;
        else if (result > 0)
            start = mid + 1;
        else
            return (void *)base + mid * size;
    }

    return NULL;
}

static int uart_setting_baud(const void *key,const void *elt)
{
    unsigned int *d = (unsigned int*)key;
    struct baudtoregs_t *b = (struct baudtoregs_t *)elt;
    if(*d > b->baud)
        return 1;
    else if(*d < b->baud)
        return -1;
    return 0;
}

int main(void) {
    struct baudtoregs_t *b;
    unsigned int baudrate = CONFIG_CONSOLE_BAUDRATE;

    if(baudrate <= baudtoregs[ARRAY_SIZE(baudtoregs) - 1].baud)
        b = (struct baudtoregs_t *) bsearch((const void*)&baudrate, (const void*)baudtoregs,ARRAY_SIZE(baudtoregs),
                               sizeof(struct baudtoregs_t), uart_setting_baud);

    quot1[0] = b->div;
    quot1[1] = b->umr;
    quot1[2] = b->uacr;

    printf("/*\n");
    printf(" * DO NOT MODIFY.\n");
    printf(" *\n");
    printf(" * This file was generated by uart_baudrate_lut\n");
    printf(" *\n");
    printf(" */\n");
    printf("\n");

    printf("#ifndef UART_BAUDRATE_LUT_H\n");
    printf("#define UART_BAUDRATE_LUT_H\n");
    printf("\n");
    printf("#define UART_BAUDRATE_DIV_BEST          0x%x\n", quot1[0]);
    printf("#define UART_UMR_BEST                   0x%x\n", quot1[1]);
    printf("#define UART_UACR_BEST                  0x%x\n", quot1[2]);
    printf("\n");
    printf("#endif /* UART_BAUDRATE_LUT_H */\n");
}
